title: "Mukul Singh | Data Analyst Portfolio"
description: "Power BI, SQL, Excel Automation and Analytics Projects Portfolio."

# Use Minimal Mistakes as a Remote Theme (Correct)
remote_theme: "mmistakes/minimal-mistakes"

# Markdown Processor
markdown: kramdown

# Plugins allowed on GitHub Pages
plugins:
  - jekyll-include-cache
  - jekyll-remote-theme

# Light Mode Skin
minimal_mistakes_skin: "default"

# Author Profile
author:
  name: "Mukul Singh"
  avatar: "/assets/images/profile.jpg"
  bio: "Data Analyst | Power BI • SQL • Excel (VBA, Power Query)"
  location: "India"
  links:
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://www.linkedin.com/in/mr-mukul-singh/"
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/dakshMukul"
    - label: "Email"
      icon: "fas fa-envelope"
      url: "mailto:Dakshmukul15@gmail.com"

# Navigation Menu
nav:
  - title: "Home"
    url: /
  - title: "Projects"
    url: /projects
  - title: "Skills"
    url: /skills
  - title: "Certifications"
    url: /certifications
  - title: "Contact"
    url: /contact
